// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfDwkYpczkJTE1zb1_EX0IM6dTcnA9GLo',
    appId: '1:168938787122:web:22201fe7aedd04588e872b',
    messagingSenderId: '168938787122',
    projectId: 'plotsklapps-dancefirst',
    authDomain: 'plotsklapps-dancefirst.firebaseapp.com',
    storageBucket: 'plotsklapps-dancefirst.firebasestorage.app',
    measurementId: 'G-2D4XTCJNY9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7tx8hvUpbGcqaGjZVXZyXm6YlIsRkyVk',
    appId: '1:168938787122:android:86b0f0d57e7a84408e872b',
    messagingSenderId: '168938787122',
    projectId: 'plotsklapps-dancefirst',
    storageBucket: 'plotsklapps-dancefirst.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA9dx6cs08L8RSAg7P_QQt05Z2ZVPlZf48',
    appId: '1:168938787122:ios:8806ce88758554408e872b',
    messagingSenderId: '168938787122',
    projectId: 'plotsklapps-dancefirst',
    storageBucket: 'plotsklapps-dancefirst.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.dancefirst',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA9dx6cs08L8RSAg7P_QQt05Z2ZVPlZf48',
    appId: '1:168938787122:ios:8806ce88758554408e872b',
    messagingSenderId: '168938787122',
    projectId: 'plotsklapps-dancefirst',
    storageBucket: 'plotsklapps-dancefirst.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.dancefirst',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfDwkYpczkJTE1zb1_EX0IM6dTcnA9GLo',
    appId: '1:168938787122:web:22201fe7aedd04588e872b',
    messagingSenderId: '168938787122',
    projectId: 'plotsklapps-dancefirst',
    authDomain: 'plotsklapps-dancefirst.firebaseapp.com',
    storageBucket: 'plotsklapps-dancefirst.firebasestorage.app',
    measurementId: 'G-2D4XTCJNY9',
  );
}
